### ISSUE TITLE
pcsx-rearmed face buttons not working

### ISSUE THREAD

**Issue by ankorite** [SinisterSpatula/Gpi3#7]
Hi, 
  I am running into a issue where the d-pad is working in my pcsx emulator but all the face buttons and combos are not. I have xboxdrv installed and ran the migrate script and updated controls. pcsx and xboxdrv where both installed from source. Mainly I am looking for the direction to troubleshoot this as I am new to both pcsx and xboxdrv. 

Cheers

**Comment by SinisterSpatula** [comment]
Hello, if the d-pad is working but face buttons are not, it sounds like maybe the buttons are not set to default bindings perhaps.  the xboxdrv scripts are going to translate the button presses to keyboard keys (default ones), and if pcsx has had those keyboard keys changed, that would cause issues, see if you can reset them to defaults (erase your pcsx config).  Also, check your runcommand log and see if xboxdrv is actually running when you launch pcsx, just launch it, and then on an SSH session run the command "nano /dev/shm/runcommand.log" and take a peek at the text contained in the log.  You should see a line like "detected joystick as retroflag usb" etc.  Or maybe theres an error showing there.

**Comment by ankorite** [comment]
Thanks for the quick reply. After work today I will do as suggested and report back. pcsx is a fresh install so default everything. BTW thanks for the work that you have put into this and your guides, very helpful and very polished.

**Comment by ankorite** [comment]
Found it. When I originally installed xboxdrv it must of failed because in the package manager it was listed as installed but the binary was missing. I reinstalled xboxdrv from source and everything is working as expected. Closing now.

**Comment by SinisterSpatula** [comment]
Awesome, glad you got it working!
